[package]
name = "pagegraph"
version = "0.1.0"
authors = ["Anton Lazarev <alazarev@brave.com>"]
edition = "2018"
readme = "README.md"

[dependencies]
xml-rs = "0.8.0"
petgraph = {version = "0.5.0", default_features = false, features = ["graphmap"]}
